# Generated by Django 3.2 on 2021-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
