# Generated by Django 3.2 on 2021-05-28 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_profile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_room_requests_created', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_room_requests_reciever', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('message', models.TextField()),
                ('msg_type', models.CharField(max_length=15, null=True)),
                ('upload_file', models.FileField(default='', null=True, upload_to='files')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_requests_reciever', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_requests_sender', to=settings.AUTH_USER_MODEL)),
                ('users_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users_room')),
            ],
        ),
    ]
